project:
  type: website
  output-dir: docs

website:
  title: "Рекомендации по подготовке курсовых и дипломных работ"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

