---
title: "Взаимодействие"
---

## Форматы обсуждения

Я считаю, что в исследовательской работе важна регулярность вазимодействия. Для этого был создан [календарь дедлайнов](timetable.html).

В соответствии с этим календарём я ожидаю, что минимум раз в месяц мы будем встречаться для обсуждения вашей работы. В идеале, это должна быть личная встреча, но при её невозможности подойдёт и созвон в Zoom и т. п. При этом для полноценного взаимодействия на созвон крайне желательно приходить с включёнными камерами и иметь возможность делиться экраном.

Для обсуждения текущих вопросов создайте чат в Телеграм с названием "Курсовая (...)" или "ВКР (...)", указав в скобках имена/фамилии участников.

## Доступ к тексту работы

Обсуждение промежуточных вариентов текста работы необходимо организовать через различные форматы облачных документов, чтобы я мог их комментировать. Два предпочительных для меня формата: гугл-документы и Overleaf. В обоих сервисах меня можно добавить по адресу dtereshch \[at\] gmail.com.

Итоговый текст в конце учебного года я рекомендую представлять мне (и загружать в LMS) в формате pdf.

## Доступ к коду

Также необходимо предоставить доступ к коду. Универсальный способ — создать репозиторий на GitHub. Подойдёт и Google Colab, если вы используете Python. В этих сервисах меня так же можно добавить по адресу dtereshch \[at\] gmail.com.

В качестве альтернативы можно создать папку на Яндекс.Диске и сложить в код в неё. В этом случае меня можно добавить в папку по адресу dtereshchenko \[at\] hse.ru.
