---
title: "Защита курсовых и дипломных работ"
---

## В предыдущих сериях...

Если вы добрались до защиты своей работы, то к этому моменту вы уже ...

-   написали и загрузили текст своей работы в LMS, а также получили или скоро получите мой отзыв на вашу работу,

-   прошли несколько промежуточных защит на НИСах.

Поэтому у вас уже должен был накопиться приличный опыт комментариев и замечаний к вашей работе и понимание того, как на нее реагируют различные люди. Рекомендую использовать этот опыт по максимуму.

Если вам делали замечания или задавали вопросы на НИСах, их вполне могут задать и на защите, так что надо быть готовыми к этому.

Если я написал в отзыве какие-либо замечания, то комиссия, скорее всего, их зачитает и попросит на них ответить, так что к этому тоже нужно заранее подготовиться.

## Почему это важно

Во-первых, оценка за защиту входит с весом 0.3 в итоговую оценку, что немало.

Во-вторых, во многом по вашей защите будут судить и о других составляющих вашей работы.

Напомню, что в своем отзыве на работу я ставлю вам оценку, но она не входит в итоговую оценку ни с каким весом. Официальную оценку вам ставит комиссия, перед которой вы защищаетесь. Хотя при желании комиссия может ориентироваться на оценку руководителя.

## Советы по защите

Ниже представлены советы по защитам курсовых и ВКР. Они составлены на основе моего собственного опыта. В основном я стараюсь ориентироваться на общую сложившуюся практику представления результатов эмпирических исслеованиях, хотя возможен и небольшой элемент субъективности.

Рекомендую ответственно подойти к этим советам. Но помните, что именно вы будете защищаться и вам важно уверено защищать свою работу. Если следование какому-нибудь совету может сломать вашу внутреннюю логику, то можете его проигнорировать (на свой страх и риск).

<details>

<summary>**Общие советы по выступлению**</summary>

-   Будьте полны энтузиазма, покажите, что ваша тема вам интересна. Но помните, что вы защищаете академическую презентацию, поэтому стиль должны быть достачно сдержанный по сравнению, например, с представлениям бизнес-проектов или театральным выступлением.

-   Будьте конкретны и расставляйте приоритеты. Цель вашего выступления --- дать комиссии понять, что и как вы сделали. Вам не хватит времени рассказать о каждой мелкой детали исследования и обо всем, что вы знаете по теме.

</details>

<details>

<summary>**Дополнительные советы по выступлению**</summary>

-   Не читайте с бумажки, не читайте с планшета, не читайте со слайдов.

-   Уложитесь в положенное время.

-   Не реагируйте агрессивно на вопросы. За любой вопрос скажите "спасибо". Ответьте на него, если ответ у вас есть. Если нет, то примите к сведению новую информацию.

-   При ответах на вопросы, старайтесь приводить объективное обоснование изходя из литературы или общей логики. Фраза "мне руководитель так сказал сделать" является плохим обоснованием.

</details>

<details>

<summary>**Общие советы по структуре презентации**</summary>

В целом можно сказать, что структура презентации должна включать все те же элементы, что и ваша работа, т. е. так или иначе в ней должны быть *вводная часть, обзор литературы, описание данных, модели и методы, заключение и обсуждение результатов*. Все перечисленное --- это не обязательно названия для ваших слайдов, а общая логическая структура выступления.

Наполнение каждоый из частей в целом должно соответствовать том, что представлено в тексте вашей работы. Все ключевые утверждения, рисунки, таблицы должны быть и в презентации.

</details>

<details>

<summary>**Дополнительные советы по структуре презентации**</summary>

-   На одних из перрвых слайдов презентации обязательно поместите исследовательский вопрос и его мотивацию, исследовательские гипотезы и экономические механизмы, которые их объясняют. А на заключительных слайдах должны появиться ответы на вопрос, результаты (содержательные) проверки гипотез.

-   Покажите, что вы читали литературу не только для того, что бы написат обзор, но и для того, чтобы обосновать собственное исследование. Помимо самого обзора, на слайдах нужно показать, что выбранные вами методы и данные соответствуют сложившейся исследовательской традиции. В конце не забудьте сравнить полученные вами результаты с результатами предыдущих исследований.

-   Из вашего выступления должно быть понятно, какие данные и методы вы использовали (и почему), поэтому не забудьте посвятить этому несколько слайдов. Обычно ожидаются слайды с описанием данных и переменных, описательными статистиками и графиками основных переменных, слайды с моделями и методами.

-   Отдельно покажите свои результаты. Обычно эмпирические результаты описываются теми же таблицами, что и в тексте работы, хотя что-то можно и сократить. Но таблицы должны быть в любом случае.

-   Не забудьте сделать заключение со своими выводами, обсуждением результатов, возможностями их применения описанием ограничений исследования.

-   Я также рекомендую сделать "запасные" слайды или что-то типа приложения к презентации. Эти слайды не должны входить в ваш основной рассказ, но могуть пригодиться для ответов на вопросы (еще раз подумайте о вопрос, которые могут вам задать). Это могут быть дополнительные графики, более подробные и дополнительные таблицы и т. п.

</details>

<details>

<summary>**Общие советы по оформлению презентации**</summary>

-   Каждый слайд и каждый элемент на слайде должен иметь какой-то смысл.
-   Используйте списки или схемы вместо сплошного текста.
-   Не используйте экзотические шрифты.
-   Делайте заголовки на слайдах.
-   Используйте разумный размер шрифта.

</details>

<details>

<summary>**Дополнительные советы по оформлению презентации**</summary>

-   Помните, что вы защищаете академическую презентацию, поэтому стиль должен быть более-менее строгим (по сравнению, например, с бизнес-презентацией).
-   Корпоративный стиль ВШЭ возможен, но не обязателен.
-   Сохраните презентацию в формате pdf. Этот формат без искажений должен открываться на любом компьютере. Другие форматы могут искажать в зависимости от версий программ, что может плохо сказаться на вашей презентации.

</details>

## Что дальше

1.  Если вы еще этого не сделали, то составьте черновик презентации, свяжитесь со мной и догоритесь о встрече для ее обсуждения. Мой опыт подсказывает, что даже у самых подготовленных студентов есть проблемы в презентациях, которые им сложно обнаружить без мнения со стороны.

2.  Совершенствуйте презентацию, готовьтесь, репетируйте.

3.  **Защищайтесь!**

4.  После защиты поделитесь со мной впечатлениями о процессе защиты (это не обязательно, но буду очень признателен). Мне очень важно знать, как другие преподаватели реагируют на то, что студенты выполняют под моим руководством. Это касается и выбранных тем и их мотивации, и примененных методов, и представления результатов. Думаю, что короткое обсуждение этого после защиты будет полезно и мне, и вам, и всем будущим поколениям студентов, так что не стоит им пренебрегать.

5.  Отдыхайте и наслаждайтесь жизнью!

6.  Если вы защитили курсовую, начинайте думать о ВКР.
