---
title: "Эмпирические результаты в курсовых и дипломных работах"
---

## Почему это важно

Предполагается, что при идеальном развитии событий в дальнейшем вы уже будете заниматься непосредственно текстом работы, а не новыми расчетами. Хотя иногда необходимость дополнительных расчетов может возникать и после этого этапа, тут все индивидуально. 

Большинство видов работ с текстом, включая написание введения, обзора литературы и т. п., могут быть бесполезными без понимания того, какие результаты получены. Все первые разделы работы должны подводить к итоговым полученным результатам. Поэтому так важно получить их сейчас, чтобы было понятно, куда вести основной текст курсовой или диплома. 


## Что включают в себя результаты

В общем случае, результаты, которым можно доверять, должны включать следующие элементы: 

1. **Базовые/описательные результаты.** Часто, хотя и не обязательно, это обычная  “модель”, оцененная методом наименьших квадратов. Скорее всего, мы заранее понимаем, что оцененные коэффициенты в этой модели нельзя интерпретировать, т. к. обычно они не являются состоятельными из-за проблемы эндогенности. Но эти результаты важно представить, чтобы показать описать данные и продемонстрировать их адекватность. 

2. **Продвинутые результаты.** Если получается, то нужно бороться за состоятельность и адекватность оценок, применяя более продвинутые методы, позволяющие преодолеть проблемы базовой модели. Это может быть борьба с эндогенностью при помощи инструментальных переменных или применение других продвинутых техник, например, использование методов работы с панельными данными, методов пространственной эконометрики и т. п. Если таких возможностей у вас нет, то, как минимум, нужно быть готовыми к обсуждению ограничений в интерпретации полученных результатов. 

3. **Анализ устойчивости результатов.** Вам нужно показать, что ваши результаты воспроизводятся (повторяются в общих чертах) при разных обстоятельствах. Или же наоборот: вам может быть важно показать, что ваши результаты чувствительны, т. е. меняются при изменении различных обстоятельств.  Например, частой практикой является осуществление анализа на подвыборках (например, можно оценивать модели отдельно для развитых и развивающихся стран, семей, проживающих в городской и сельской местности, и т. п.) и на различных периодах (это может быть просто “техническое” разделение на подпериоды или более осмысленное, в зависимости от контекста, например до пандемии и во время пандемии). Еще одним способом показать устойчивость результатов является использование других показателей для измерения ваших основных переменных.


## Результаты --- это не только оценки коэффициентов

Помните, что эконометрический анализ не обязательно сводится только к интерпретации оцененных коэффициентов. Если ваши модели являются нелинейными или включают важные нелинейные эффекты, то анализ коэффициентов нужно дополнять анализом предельных эффектов. А иногда показатели эластичности важнее для ответа на исследовательский вопрос, чем сами коэффициенты. 


## О статистической значимости

Лично я считаю, что результаты не обязательно должны быть статистики значимыми. Если вы ответственно поработали с данными и честно оценили свои модели, то отрицательный результат тоже является результатом и позволяет дать ответ на исследовательский вопрос. Однако также необходимо держать в уме, что в научном сообществе существуют несколько искаженные представления, при которых статистически значимые результаты воспринимаются более позитивно. В целом, старайтесь, чтоб вся ваша работа и результаты в том числе были в достаточной мере обоснованы. 