---
title: "Рекомендации по структуре и разделам курсовых и дипломных работ"
---

## Коротко

Строгих требований к структуре курсовой/ВКР нет. Общее требование --- структура должна быть ясной и понятной, способствовать логичному изложению мысли.

Часто структура научной работы зависит области, в которой проводится исследование. Поэтому основным источником вдохновения для вас могут быть научные статьи по вашей теме. По мере ознакомления со статьями, у вас должно сложиться общее впечатление о том, какая структура принята в области, к которой относится ваша работа.

Как правило, каким-то образом обособляются следующие элементы работы:

-   Введение

-   Обзор литературы

-   Методы

-   Данные

-   Результаты

-   Заключение

Иными словами, вы должны раскрыть в своей работе:

-   зачем вы это делали (введение)

-   что и как вы делали (методы)

-   с чем вы это делали (данные)

-   что в итоге получили (результаты и заключение)

## Подробно

Для эмпирических курсовых/ВКР я рекомендую примерно следующую структуру (она может меняться в зависимости от области исследований и хода вашей работы):

1.  **Введение**
    a.  Мотивация: почему то, что вы изуаете важно
    b.  Может включать в себя краткий обзор основных исследований по теме
    c.  Исследовательский вопрос, исследовательская гипотеза, экономический механизм, обосновывающий гипотезу
2.  **Обзор литературы** (иногда)

<!-- -->

a.  Основные исследования по теме, который призван дать понять текущее состояние исследовательской области (иногда эта часть обзора приводится во введении)
b.  Обзор работ, наиболее близких к контексту проводимого исследования, например, обзор исследований данной проблемы в России (иногда эта часть обзора представляется в разделах "Введение" или "Контекст")

<!-- -->

3.  **Контекст**
    a.  Описание особенностей развития какой-либо сферы, отрасли, национальных особенностей
    b.  Может включать обзор литературы про Россию
4.  **Данные и переменные**
    a.  Описание источников, датасета, процесса сбора
    b.  Описание переменных (зависимой переменной, переменной интереса, контрольных переменных и т. п.)
    c.  Описательные статистики
5.  **Методология**
    a.  Регрессионные модели
    b.  Стратегия оценивания
    c.  Может включать в себя описание программного обеспечения, использованного при работе, ссылки на код, исходные данные и т. п.
6.  **Результаты**
    a.  Описательные/предварительные результаты (иногда)
    b.  Основные результаты
    c.  Robustness checks (различные проверки, призванные подвердить, что ваши результаты являлются устойчивыми при изменении спецификаций, данных и т. п.
7.  **Заключение**
    a.  Подведение итогов
    b.  Обсуждение результатов (их экономическая осмысленность, сопоставление с результатами предыдущих исследований)
    c.  Рекомендации на основе полученных результатов (как и кто их может использовать?)
    d.  Вклад, который полученные результаты привносят в имеющееся знание
    e.  Направления для будущих исследований
    f.  Угрозы внутренней и внешней валидности исследования
