---
title: "Дедлайны"
---

## Общие принципы

Я неприемлю стратегии "делать все в последний момент", поэтому я ожидаю от вас, что вы включитесь в работу сразу и будете поддерживать достаточный уровень активности на протяжении всего учебного года.

## Дедлайны

В процессе работы я ожидаю прохождение нескольких контрольных точек. Ниже представлены основные требования и примерные сроки. При непрохождении любой из контрольных точек я оставляю за собой право отказаться от руководства. Даты указаны примерно, но в целом прохождение контрольных точек ожидается в начале каждого месяца.

Все дедлайны записаны в специальный [гугл-календарь](https://calendar.google.com/calendar/u/0?cid=YWRmZTAzZTg0ZTE1MDVlMTQ2NDRiNzg0NTUxYjkxYTdjOWZhMWY4NjgyZDYzOWI2ZGVmMTAzYzM0NWRkZjI4N0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t). По ссылке вы можете к нему присоединиться, чтобы получать уведомления. С календарем или без него считайте, что **первого числа каждого месяца пора связываться со мной для обсуждения очередной контрольной точки**. 

Наличие определенного задания для контрольной точки не означает, что нужно обязательно отказываться от всех остальных вариантов активностей. Например, чтение литературы и пополнение обзора, а также работа с данными могут проходить на протяжении всего срока работы. 

### Начало работы с литературой

**Требования**: прочитать и вникнуть хотя бы в три статьи, относящиеся к теме работы. 

**Форма отчета**: обсуждение с руководителем, начало заполнения таблицы с обзором эмпирических статей.

**Срок**: 1 ноября.


### Продолжение работы с литературой

**Требования**: продолжать поиск и чтение литературы, заполнять таблицу с обзором эмпирических статей, писать черновик обзора литературы. 

**Форма отчета**: обсуждение с руководителем, сравнительная таблица эмпирических статей, черновик обзора литературы.

**Срок**: 1 декабря.


### Подготовка Research proposal

**Требования**: продолжать чтение литературы, заниматься поиском данных, подготовить Research proposal.

**Форма отчета**: обсуждение с руководителем, текст Research proposal.

**Срок**: 1 января.


### Сбор и разведывательный анализ данных

**Требования**: собрать данные и провести их обработку, провести разведывательный анализ данных

**Форма отчета**: обсуждение с руководителем, файлы с данными, файлы с необходимыми графиками и таблицами, скрипт с кодом.

**Срок**: 1 февраля.


### Получение предварительных результатов

**Требования**: проведение эмпирического анализа для ответа на поставленный вопрос. 

**Форма отчета**: обсуждение с руководителем, таблицы с результатами, скрипт с кодом.

**Срок**: 1 марта.


### Получение итоговых результатов

**Требования**: доработка эмпирического анализа, описание полученных результатов.

**Форма отчета**: обсуждение с руководителем, скрипт с кодом, текст с таблицами и описанием результатов.

**Срок**: 1 апреля. 


### Черновой вариант работы

**Требования**: подготовить черновой, но полный вариант работы. 

**Форма отчета**: черновой вариант работы, обсуждение с руководителем.  

**Срок**: 1 мая.


### Итоговый вариант работы

**Требования**: подготовить и загрузить в LMS для проверки итоговый вариант работы, подготовка презентации для защиты. 

**Форма отчета**: загрузка в LMS итогового варианта работы, обсуждение презентации с руководителем.

**Срок**: устанавливается Учебным офисом.