---
title: "Советы"
---

## Что это

На этой страничке вы можете посмотреть некоторые советы по работе над курсовой/ВКР.

РАЗДЕЛ БУДЕТ ПОПОЛНЯТЬСЯ В ТЕЧЕНИЕ ГОДА.

## Советы по разделам

Для просмотра советов щелкните по соответствующей ссылке.

-   [Поиск и обзор литературы](lit.html). 

<details>

<summary>Поиск и обзор литературы</summary>

Количество источников в списке литературы никак не регламентируется, но по моей субъективной оценке в вашем списке литературы должно быть хотя бы 20 источников, большинство из которых --- англоязычные эмпирические, опубликованные в хороших журналах.

Критерий, который я могу предложить для определения хороших журналов, такой. Журнал должен находиться в первом или втором квартиле (Q1 или Q2) в области "Economics, Econometrics". Квартили журналом рекомендую смотреть на сайте [SJR](https://www.scimagojr.com/).

В процессе чтения эмпирических статей я рекомендую заносить ключевую информацию о них в таблицу [примерно такого вида](https://docs.google.com/spreadsheets/d/10Lcw_3SHWKwL8YY8o91tbtVE0EdSW14gPCcQzxEJzfw/edit?usp=sharing).

При оформлении ссылок на литературу, а также списка литературы предпочтителен APA-style. Примеры оформления можно посмотреть по [ссылке](https://www.scribbr.com/category/apa-examples/).

</details>

<details>

<summary>Структура Research proposal</summary>

Составление Research proposal (aka "Предложение по исследованию") является первым содержательным этапом при подготовке курсовой/ВКР.

Как правило, Research proposal включает в себя описание следующих элементов:

1.  **Исследовательский вопрос**: что хотите исследовать, и почему этот вопрос интересен (мотивация исследования, в идеале --- со ссылками на литературу). Отталкивайтесь от интересного явления, которое хотите объяснить или исследовать.

2.  Выдвигаемые **гипотезы** относительно исследовательского вопроса (формулировка в обычном, смысловом контексте). Обоснование гипотез --- почему и из каких соображений они выдвигаются: какой механизм обеспечивает те причинно-следственные связи, которые лежат в основе ваших гипотез. Здесь тоже в идеале нужно использовать при аргументации ссылки на литературу.

3.  Какие **данные** для этого понадобятся или уже собраны: что должно быть единицей наблюдения, какая должна быть выборка, какой тип данных. Потенциальный или фактический **источник данных** (или источники), т. е. база данных, на которой такое исследование может быть проведено: название, описание (что, кем, когда и как собиралось, измерялось, описывалось и т.п.), ссылка на страницу в интернете.

4.  Какие **переменные**, т. е. характеристики (признаки) объектов наблюдения необходимы. Какие переменные доступны в имеющихся источниках: за какой период, для какой выборки. Описание этих переменных (единицы измерения, особенности измерения и т. п.). Какие из них являются переменными интереса, а какие --- контрольными переменными.

5.  Спецификация **модели**: набор регрессоров, форма зависимости. Обоснование модели (из общих смысловых и экономических соображений).

6.  **Эконометрическая формулировка гипотез**: постановка гипотез в содержательной и статистической формах. Выбор и обоснование критерия для проверки гипотез.

7.  **Policy Conclusions** (возможные практические применения результатов исследования): кому результаты такого исследования могут быть полезны и как их можно использовать.

</details>
