---
title: "Темы"
---

## Общее

Я руковожу эмпирическими работами, предполающими серьезную работу с данными, а также ответы на содержательные экономические вопросы при помощи методов статистики и эконометрики. Поэтому от вас я тоже ожидаю живой интерес к эмпирической работе, в т. ч. желание осваивать методы, выходящие за рамки базовых курсов статистики и эконометрики (при необходимости).

У меня есть собственные научные интересы, в рамках которых я формулирую потенциальные темы для исследований. Наиболее надежным путем для студентов я считаю выбор одной из таких тем, т. к. по ним я смогу вас больше консультировать и направлять. Возможен и такой вариант, при котором вы сами формулируете тему исследования. В этом случае я могу согласиться или не согласиться руководить работой, но даже если соглашусь, основная нагрузка по разработке темы ляжет на ваши плечи.

## 2023-24 учебный год

В 2023-24 учебном году у меня нет открытого перечня тем, но я готов обсуждать (или уже обсудил) конкретные темы с заинтересованными студентами. В основном, темы формулируются в рамках следующих направлений:

-   оценка спроса на продукты питания;

-   анализ ценообразования в российском ритейле продуктов питания;

-   анализ пространственной конкуренции между ритейлерами на рынке продуктов питания.

## Архив

Ниже можно посмотреть список тем, которыми я руководил в предыдущие годы, а также оценки, полученные за эти темы.

<details>
<summary>2022-23</summary>

| Тип      	| Тема                                                                                                                                  	| Оценка 	|
|----------	|---------------------------------------------------------------------------------------------------------------------------------------	|--------	|
| ВКР      	| Применение методов машинного обучения в прогнозировании банкротства                                                                   	| 9      	|
| ВКР      	| Влияние обменного курса на розничные цены                                                                                             	| 7      	|
| ВКР      	| Экономический рост и диверсификация торговых отношений: эмпирический анализ российских регионов                                       	| 9      	|
| ВКР      	| Как женская эмансипация повлияла на экономический рост                                                                                	| 5      	|
| Курсовая 	| Детское здоровье и занятость родителей: эмпирический анализ российских домохозяйств                                                   	| 10     	|
| Курсовая 	| Эмпирический анализ пространственной конкуренции между сетевыми ритейлерами в Санкт-Петербурге (на примере Магнита, Пятерочки, Дикси) 	| 8      	|
| Курсовая 	| Эмпирический анализ пространственной конкуренции между сетевыми ритейлерами в Санкт-Петербурге (на примере хард-дискаунтеров)         	| 4      	|
| Курсовая 	| Совмещение работы и учебы. Как это влияет на заработную плату выпускника?                                                             	| 8      	|
| Курсовая 	| Неравенство в потреблении продуктов питания: эмпирический анализ российских домохозяйств                                              	| 8      	|
| Курсовая 	| Эмпирический анализ стратегий онлайн-цен сетевых продуктовых ритейлеров                                                               	| 9      	|

</details>

<details>
<summary>2021-22</summary>

| Тип      	| Тема                                                                                          	| Оценка 	|
|----------	|-----------------------------------------------------------------------------------------------	|--------	|
| ВКР      	| Эмпирическая оценка спроса на продукты питания в России                                       	| 8      	|
| ВКР      	| Детское здоровье и доходы родителей: эмпирический анализ российских домохозяйств              	| 9      	|
| Курсовая 	| Экономический рост и культурное многообразие: эмпирический анализ российских регионов         	| 8, 7   	|
| Курсовая 	| Разнообразие видов деятельности и экономический рост: эмпирический анализ российских регионов 	| 7      	|
| Курсовая 	| Анализ пространственной конкуренции продуктового ритейла                                      	| 8      	|

</details>


<details>
<summary>2020-21</summary>

| Тип      	| Тема                                                                                              	| Оценка 	|
|----------	|---------------------------------------------------------------------------------------------------	|--------	|
| ВКР      	| Эмпирический анализ обусловленного доходами неравенства здоровья среди детей Российской Федерации 	| 7      	|
| ВКР      	| Гендерные различия в потребительских предпочтениях: эмпирический анализ рынка фитнес-услуг в РФ   	| 8      	|
| ВКР      	| Экономический рост и цифровизация: эмпирический анализ российских регионов                        	| 7      	|
| Курсовая 	| Смена губернатора и региональные экономические показатели: эмпирический анализ                    	| 9      	|
| Курсовая 	| Психическое здоровье и неравенство доходов: эмпирический анализ стран мира                        	| 9      	|
| Курсовая 	| Эмпирическая оценка межрегиональной мобильности капитала в России                                 	| 3      	|
| Курсовая 	| Детское здоровье и доходы родителей: эмпирический анализ российских домохозяйств                  	| 9      	|

</details>


<details>
<summary>2019-20</summary>

| Тип      	| Тема                                                                                      	| Оценка   	|
|----------	|-------------------------------------------------------------------------------------------	|----------	|
| ВКР      	| Демократические институты и инновационное развитие фирм: анализ данных по регионам России 	| 5        	|
| ВКР      	| Инновации и экономический рост: эмпирический анализ стран мира                            	| 6        	|
| ВКР      	| Эконометрический анализ влияния инноваций на экономический рост в российских регионах     	| недопуск 	|
| Курсовая 	| Институты и неравенство: эмпирический анализ российских регионов                          	| 7        	|

</details>


<details>
<summary>2018-19</summary>

| Тип      	| Тема                                           	| Оценка 	|
|----------	|------------------------------------------------	|--------	|
| Курсовая 	| Влияние инноваций на экономический рост страны 	| 7      	|

</details>